### 
@url = http://localhost:8000

### Base URL
GET {{url}} 

### Authentication
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6ImFkbWluMkBnbWFpbC5jb20iLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3NTA3NTg5MTYsImV4cCI6MTc1MDc2MjUxNn0.ukf2WyG0cs2nM4MHQ8qpAtjo4sRmgUq8UtSItl1p33E
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI0LCJlbWFpbCI6InN0ZXZlcml1a2lAZ21haWwuY29tIiwicm9sZSI6IlNhbGVzIiwiaWF0IjoxNzQ5NTQzNzU2LCJleHAiOjE3NTAxNDg1NTZ9.I2S2aB4KUtGSa1kISTBBHJOQmVP-ODofcRx6p-Uy98s
### Cache Metrics
GET {{url}}/cache-metrics
Authorization: Bearer {{token}}

### Cache Management
POST {{url}}/cache
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "user_123",
  "value": "John Doe Profile Data",
  "ttl": 3600
}
### login Sales
POST {{url}}/auth/signin
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "steveriuki@gmail.com",
  "password": "securepassword"
}

### login User
POST {{url}}/auth/signin
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "securepassword"
}

### Logout
POST {{url}}/auth/signout/12
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 12
}

### Refresh Tokens
POST {{url}}/auth/refresh/12
Authorization: Bearer {{refreshToken}}
Content-Type: application/json

{
  "userId": 12,
  "refreshToken": "{{refreshToken}}"
}

###
POST {{url}}/auth/signup
Content-Type: application/json

{
  "first_name": "Steve",
  "last_name": "Riuki",
  "email": "riukisteve@gmail.com",
  "password": "Coding@21",
  "role": "Customer"
}

### login Admin
POST {{url}}/auth/signin
Content-Type: application/json

{
  "email": "admin2@gmail.com",
  "password": "securepassword"
}


###
POST {{url}}/seed
Authorization: Bearer {{token}}
